### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by BobGu** [kelshadarby/mod_0_skills#1]
Hi @kelshadarby! Thanks for your hard work on this. I like your use of multiple attributes in your first class to arrive at the number of dirty utensils. 

- [x] It looks like there is some convention mismatching in your `Silverware` example. Can you either use all `snakeCase` if you are in the front end program, or all `camel_case` if you are in the back end program?

**Comment by kelshadarby** [comment]
Hi @BobGu! 

Whoops! Thank you for letting me know, I believe this issue arose when I tried to change from `snake_case` to `camelCase` halfway through. I was still a bit confused on when to use which and if one was more professional/preferred than the other. I have since realized which to use, since I am back end and will use `snake_case` from here on out.

I have updated all files in the `classes` directory to match the back end `snake_case`.
